#!/usr/bin/env python3
"""
ClawEDR macOS Policy Applicator.

Reads the universal compiled_policy.json and the user's exemption list
from ~/.clawedr/user_rules.yaml, then generates a merged Seatbelt LISP
profile (clawedr_merged.sb) that excludes exempted rules.

This script is invoked by the Dashboard or manually by the user
whenever user_rules.yaml changes.

Usage:
    python3 apply_macos_policy.py [--policy PATH] [--output PATH]
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

# Add parent directory to path so we can import shared modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from shared.user_rules import get_exempted_rule_ids, get_custom_rules

logger = logging.getLogger("clawedr.apply_macos_policy")

DEFAULT_POLICY = "/usr/local/share/clawedr/compiled_policy.json"
DEFAULT_OUTPUT = "/usr/local/share/clawedr/clawedr.sb"

_SB_HEADER = """\
;;; ClawEDR Seatbelt Profile — generated by apply_macos_policy.py
;;; Includes user exemptions from ~/.clawedr/user_rules.yaml
(version 1)
(allow default)
"""

_MACOS_BIN_PREFIXES = [
    "/usr/bin/", "/usr/sbin/", "/usr/local/bin/", "/opt/homebrew/bin/",
    "/opt/local/bin/",
]


def generate_seatbelt(policy: dict, exempted: set[str]) -> str:
    """Generate a macOS Seatbelt (.sb) LISP profile from the universal policy.

    Rules whose ID is in `exempted` are skipped entirely.
    """
    lines = [_SB_HEADER]

    # ── Blocked paths ──
    blocked_paths = policy.get("blocked_paths", {}).get("macos", {})
    if blocked_paths:
        lines.append(";;; --- Blocked paths ---")
        for rule_id, path in blocked_paths.items():
            if rule_id in exempted:
                lines.append(f";;; [{rule_id}] EXEMPTED by user: {path}")
                continue
            sb_path = path.replace("~", "/Users/*")
            lines.append(f";;; [{rule_id}]")
            if "*" in sb_path:
                regex_path = sb_path.replace("*", "[^/]+")
                lines.append(f'(deny file-read* (regex #"^{regex_path}"))')
                lines.append(f'(deny file-write* (regex #"^{regex_path}"))')
            else:
                lines.append(f'(deny file-read* (subpath "{sb_path}"))')
                lines.append(f'(deny file-write* (subpath "{sb_path}"))')

    # ── Blocked executables ──
    execs = policy.get("blocked_executables", {})
    if execs:
        lines.append(";;; --- Blocked executables ---")
        for rule_id, name in execs.items():
            if rule_id in exempted:
                lines.append(f";;; [{rule_id}] EXEMPTED by user: {name}")
                continue
            lines.append(f";;; [{rule_id}]")
            if "/" in name:
                lines.append(f'(deny process-exec (literal "{name}"))')
            else:
                for prefix in _MACOS_BIN_PREFIXES:
                    lines.append(
                        f'(deny process-exec (literal "{prefix}{name}"))'
                    )

    # ── Blocked domains (comment-only, enforced by log_tailer.py) ──
    blocked_domains = policy.get("blocked_domains", {})
    if blocked_domains:
        lines.append(";;; --- Blocked domains (enforced by log_tailer.py, not kernel-level) ---")
        for rule_id, domain in blocked_domains.items():
            if rule_id in exempted:
                lines.append(f";;;   [{rule_id}] EXEMPTED by user: {domain}")
            else:
                lines.append(f";;;   [{rule_id}] {domain}")

    # ── Custom deny rules ──
    custom_rules = policy.get("deny_rules", {}).get("macos", {})
    if custom_rules:
        lines.append(";;; --- Custom deny rules ---")
        for rule_id, custom in custom_rules.items():
            if rule_id in exempted:
                lines.append(f";;; [{rule_id}] EXEMPTED by user")
                continue
            if isinstance(custom, str):
                lines.append(f";;; [{rule_id}]")
                lines.append(custom)

    lines.append("")
    return "\n".join(lines)


def notify_restart() -> None:
    """Send a macOS notification prompting the user to restart OpenClaw."""
    try:
        subprocess.run(
            [
                "osascript", "-e",
                'display notification "User rules applied. '
                'Please restart OpenClaw for changes to take effect." '
                'with title "ClawEDR"',
            ],
            check=True,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    logger.info("User notified to restart OpenClaw")


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    parser = argparse.ArgumentParser(description="Generate ClawEDR macOS Seatbelt profile")
    parser.add_argument("--policy", default=DEFAULT_POLICY, help="Path to compiled_policy.json")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output .sb file path")
    args = parser.parse_args()

    # Load universal policy
    try:
        with open(args.policy) as f:
            policy = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        logger.error("Failed to load policy from %s: %s", args.policy, exc)
        return 1

    # Load user exemptions
    exempted = get_exempted_rule_ids()
    if exempted:
        logger.info("User exemptions: %s", ", ".join(sorted(exempted)))
    else:
        logger.info("No user exemptions active")

    # Merge custom rules into policy
    custom = get_custom_rules()
    if custom:
        logger.info("Merging %d custom user rules into policy", len(custom))
        for rule in custom:
            rid = rule.get("id", "")
            rtype = rule.get("type", "")
            val = rule.get("value", "")
            plat = rule.get("platform", "both")
            if plat not in ("both", "macos"):
                continue  # Skip Linux-only custom rules on macOS

            if rtype == "executable":
                policy.setdefault("blocked_executables", {})[rid] = val
            elif rtype == "domain":
                policy.setdefault("blocked_domains", {})[rid] = val
            elif rtype == "path":
                policy.setdefault("blocked_paths", {}).setdefault("macos", {})[rid] = val
            elif rtype == "argument":
                policy.setdefault("deny_rules", {}).setdefault("macos", {})[rid] = val

    # Generate Seatbelt profile
    sb_content = generate_seatbelt(policy, exempted)

    # Write output
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as f:
        f.write(sb_content)
    logger.info("Seatbelt profile written to %s", output)

    # Notify user to restart
    notify_restart()

    return 0


if __name__ == "__main__":
    sys.exit(main())
