"""
ClawEDR Universal Policy Compiler.

Consumes the merged threat data (from the Threat Aggregator) and produces:
  - deploy/compiled_policy.json  (Linux eBPF policy)
  - deploy/macos/clawedr.sb      (macOS Seatbelt LISP profile)
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEPLOY_DIR = PROJECT_ROOT / "deploy"
MERGED_RULES_PATH = PROJECT_ROOT / "builder" / ".merged_rules.json"


def load_merged_rules(path: Path = MERGED_RULES_PATH) -> dict[str, Any]:
    """Load the merged rules JSON produced by the Threat Aggregator."""
    logger.info("Loading merged rules from %s", path)
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Linux: compiled_policy.json
# ---------------------------------------------------------------------------

def compile_linux_policy(rules: dict[str, Any]) -> dict[str, Any]:
    """Build the Linux eBPF policy structure.

    The policy is a flat mapping consumed by bpf_hooks.c / monitor.py.
    """
    policy: dict[str, Any] = {
        "version": rules.get("version", "2.0"),
        "blocked_executables": rules.get("blocked_executables", []),
        "blocked_domains": rules.get("blocked_domains", []),
        "malicious_hashes": rules.get("malicious_hashes", []),
        "blocked_paths": rules.get("blocked_paths", {}).get("linux", []),
        "deny_rules": [],
    }

    for rule in rules.get("custom_deny_rules", {}).get("linux", []):
        policy["deny_rules"].append(rule)

    return policy


def write_linux_policy(policy: dict[str, Any], dest: Path | None = None) -> Path:
    dest = dest or DEPLOY_DIR / "compiled_policy.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w") as f:
        json.dump(policy, f, indent=2)
    logger.info("Linux policy written to %s", dest)
    return dest


# ---------------------------------------------------------------------------
# macOS: clawedr.sb (Seatbelt LISP)
# ---------------------------------------------------------------------------

_SB_HEADER = """\
;;; ClawEDR Seatbelt Profile — auto-generated by compiler.py
;;; Do not edit by hand; regenerate with ./main.py compile
(version 1)
(allow default)
"""


_MACOS_BIN_PREFIXES = [
    "/usr/bin/", "/usr/sbin/", "/usr/local/bin/", "/opt/homebrew/bin/",
    "/opt/local/bin/",
]


def compile_macos_seatbelt(rules: dict[str, Any]) -> str:
    """Generate a macOS Seatbelt (.sb) LISP profile.

    In Seatbelt LISP the last matching rule wins, so (allow default)
    goes first and specific deny rules follow to override it.
    """
    lines = [_SB_HEADER]

    # ── Blocked paths ──
    lines.append(";;; --- Blocked paths ---")
    for path in rules.get("blocked_paths", {}).get("macos", []):
        sb_path = path.replace("~", "/Users/*")
        if "*" in sb_path:
            regex_path = sb_path.replace("*", "[^/]+")
            lines.append(f'(deny file-read* (regex #"^{regex_path}"))')
            lines.append(f'(deny file-write* (regex #"^{regex_path}"))')
        else:
            lines.append(f'(deny file-read* (subpath "{sb_path}"))')
            lines.append(f'(deny file-write* (subpath "{sb_path}"))')

    # ── Blocked executables ──
    execs = rules.get("blocked_executables", [])
    if execs:
        lines.append(";;; --- Blocked executables ---")
        for name in execs:
            if "/" in name:
                lines.append(f'(deny process-exec (literal "{name}"))')
            else:
                for prefix in _MACOS_BIN_PREFIXES:
                    lines.append(
                        f'(deny process-exec (literal "{prefix}{name}"))'
                    )

    # Seatbelt does not support hostname-based filters; domain blocking is
    # enforced at the application layer by log_tailer.py / openclaw wrapper.
    blocked_domains = rules.get("blocked_domains", [])
    if blocked_domains:
        lines.append(";;; --- Blocked domains (enforced by log_tailer.py, not kernel-level) ---")
        for domain in blocked_domains:
            lines.append(f';;;   - {domain}')

    # ── Custom deny rules (raw Seatbelt directives) ──
    custom_rules = rules.get("custom_deny_rules", {}).get("macos", [])
    if custom_rules:
        lines.append(";;; --- Custom deny rules ---")
        for custom in custom_rules:
            if isinstance(custom, str):
                lines.append(custom)

    lines.append("")
    return "\n".join(lines)


def write_macos_seatbelt(sb_content: str, dest: Path | None = None) -> Path:
    dest = dest or DEPLOY_DIR / "macos" / "clawedr.sb"
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w") as f:
        f.write(sb_content)
    logger.info("macOS Seatbelt profile written to %s", dest)
    return dest


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def compile_all(merged_path: Path = MERGED_RULES_PATH) -> None:
    """Compile both Linux and macOS policies from merged rules."""
    rules = load_merged_rules(merged_path)

    linux_policy = compile_linux_policy(rules)
    write_linux_policy(linux_policy)

    sb_content = compile_macos_seatbelt(rules)
    write_macos_seatbelt(sb_content)

    logger.info("Compilation complete.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    compile_all()
