"""
ClawEDR Universal Policy Compiler.

Consumes the merged threat data (from the Threat Aggregator) and produces:
  - deploy/compiled_policy.json  (universal policy with Rule IDs)
  - deploy/macos/clawedr.sb      (macOS Seatbelt LISP profile)

All rules carry their Rule ID so that the Shield daemons and the
Dashboard can reference them precisely.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEPLOY_DIR = PROJECT_ROOT / "deploy"
MERGED_RULES_PATH = PROJECT_ROOT / "builder" / ".merged_rules.json"


def load_merged_rules(path: Path = MERGED_RULES_PATH) -> dict[str, Any]:
    """Load the merged rules JSON produced by the Threat Aggregator."""
    logger.info("Loading merged rules from %s", path)
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Linux: compiled_policy.json
# ---------------------------------------------------------------------------

def compile_linux_policy(rules: dict[str, Any]) -> dict[str, Any]:
    """Build the Linux eBPF policy structure.

    The policy is a flat mapping consumed by bpf_hooks.c / monitor.py.
    All entries are keyed by Rule ID.
    """
    policy: dict[str, Any] = {
        "version": rules.get("version", "2.0"),
        "blocked_executables": dict(rules.get("blocked_executables", {})),
        "blocked_domains": dict(rules.get("blocked_domains", {})),
        "blocked_ips": dict(rules.get("blocked_ips", {})),
        "malicious_hashes": dict(rules.get("malicious_hashes", {})),
        "blocked_paths": dict(rules.get("blocked_paths", {}).get("linux", {})),
        "deny_rules": {},
        "rule_metadata": dict(rules.get("rule_metadata", {})),
    }

    for rule_id, rule in rules.get("custom_deny_rules", {}).get("linux", {}).items():
        policy["deny_rules"][rule_id] = rule

    return policy


def compile_universal_policy(rules: dict[str, Any]) -> dict[str, Any]:
    """Build a universal policy containing rules for both OSes.

    This is the single artifact shipped to end-users. The local Shield
    daemons filter rules by platform and apply user exemptions at runtime.
    """
    policy: dict[str, Any] = {
        "version": rules.get("version", "2.0"),
        "blocked_executables": dict(rules.get("blocked_executables", {})),
        "blocked_domains": dict(rules.get("blocked_domains", {})),
        "blocked_ips": dict(rules.get("blocked_ips", {})),
        "malicious_hashes": dict(rules.get("malicious_hashes", {})),
        "blocked_paths": {
            "linux": dict(rules.get("blocked_paths", {}).get("linux", {})),
            "macos": dict(rules.get("blocked_paths", {}).get("macos", {})),
        },
        "deny_rules": {
            "linux": dict(rules.get("custom_deny_rules", {}).get("linux", {})),
            "macos": dict(rules.get("custom_deny_rules", {}).get("macos", {})),
        },
        "rule_metadata": dict(rules.get("rule_metadata", {})),
    }
    return policy


def write_linux_policy(policy: dict[str, Any], dest: Path | None = None) -> Path:
    dest = dest or DEPLOY_DIR / "compiled_policy.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w") as f:
        json.dump(policy, f, indent=2)
    logger.info("Linux policy written to %s", dest)
    return dest


# ---------------------------------------------------------------------------
# macOS: clawedr.sb (Seatbelt LISP)
# ---------------------------------------------------------------------------

_SB_HEADER = """\
;;; ClawEDR Seatbelt Profile — auto-generated by compiler.py
;;; Do not edit by hand; regenerate with ./main.py compile
(version 1)
(allow default)
"""


_MACOS_BIN_PREFIXES = [
    "/usr/bin/", "/usr/sbin/", "/usr/local/bin/", "/opt/homebrew/bin/",
    "/opt/local/bin/",
]


def compile_macos_seatbelt(rules: dict[str, Any]) -> str:
    """Generate a macOS Seatbelt (.sb) LISP profile.

    In Seatbelt LISP the last matching rule wins, so (allow default)
    goes first and specific deny rules follow to override it.

    Each rule is annotated with its Rule ID as a comment.
    """
    lines = [_SB_HEADER]

    # ── Blocked paths ──
    lines.append(";;; --- Blocked paths ---")
    blocked_paths = rules.get("blocked_paths", {}).get("macos", {})
    for rule_id, path in blocked_paths.items():
        sb_path = path.replace("~", "/Users/*")
        lines.append(f";;; [{rule_id}]")
        if "*" in sb_path:
            regex_path = sb_path.replace("*", "[^/]+")
            lines.append(f'(deny file-read* (regex #"^{regex_path}"))')
            lines.append(f'(deny file-write* (regex #"^{regex_path}"))')
        else:
            lines.append(f'(deny file-read* (subpath "{sb_path}"))')
            lines.append(f'(deny file-write* (subpath "{sb_path}"))')

    # ── Blocked executables ──
    execs = rules.get("blocked_executables", {})
    if execs:
        lines.append(";;; --- Blocked executables ---")
        for rule_id, name in execs.items():
            lines.append(f";;; [{rule_id}]")
            if "/" in name:
                lines.append(f'(deny process-exec (literal "{name}"))')
            else:
                for prefix in _MACOS_BIN_PREFIXES:
                    lines.append(
                        f'(deny process-exec (literal "{prefix}{name}"))'
                    )

    # Seatbelt does not support hostname-based filters; domain blocking is
    # currently unsupported on macOS (no kernel-level hostname enforcement).
    # Domain monitoring is handled by log_tailer.py via lsof polling.
    blocked_domains = rules.get("blocked_domains", {})
    if blocked_domains:
        lines.append(";;; --- Blocked domains (monitoring-only on macOS via log_tailer.py) ---")
        for rule_id, domain in blocked_domains.items():
            lines.append(f';;;   [{rule_id}] {domain}')

    # Seatbelt cannot filter by specific IP address (only * or localhost).
    # IP monitoring is handled by log_tailer.py via lsof polling.
    blocked_ips = rules.get("blocked_ips", {})
    if blocked_ips:
        lines.append(";;; --- Blocked IPs (monitoring-only on macOS via log_tailer.py) ---")
        for rule_id, ip_addr in blocked_ips.items():
            lines.append(f';;;   [{rule_id}] {ip_addr}')

    # ── Custom deny rules (raw Seatbelt directives) ──
    custom_rules = rules.get("custom_deny_rules", {}).get("macos", {})
    if custom_rules:
        lines.append(";;; --- Custom deny rules ---")
        for rule_id, custom in custom_rules.items():
            if isinstance(custom, str):
                lines.append(f";;; [{rule_id}]")
                lines.append(custom)

    lines.append("")
    return "\n".join(lines)


def write_macos_seatbelt(sb_content: str, dest: Path | None = None) -> Path:
    dest = dest or DEPLOY_DIR / "macos" / "clawedr.sb"
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w") as f:
        f.write(sb_content)
    logger.info("macOS Seatbelt profile written to %s", dest)
    return dest


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def compile_all(merged_path: Path = MERGED_RULES_PATH) -> None:
    """Compile both Linux and macOS policies from merged rules."""
    rules = load_merged_rules(merged_path)

    # Write the universal compiled_policy.json (used by both platforms at runtime)
    universal_policy = compile_universal_policy(rules)
    write_linux_policy(universal_policy)

    sb_content = compile_macos_seatbelt(rules)
    write_macos_seatbelt(sb_content)

    logger.info("Compilation complete.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    compile_all()
